apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: wangxiyuan
  kubernetes.ops.region: shanghai
kind: Kustomization
namespace: merlin
resources:
- service.yaml
- deployment.yaml
- autoscaler.yaml
- pvc.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/gitea/merlin-space-test
  newTag: release-39a255
