apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: shanghai-test-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: gongzhuangbang
  kubernetes.ops.region: shanghai
kind: Kustomization
namespace: easysoftware
resources:
- service.yaml
- deployment.yaml
- autoscaler.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/easysoftware/easysoftware-website-test
  newTag: master-0821f2
