resources:
- namespace.yaml
- sa.yaml
- networkpolicy.yaml
- merlin-server
- merlin-website
- merlin-docs
- hook-delivery
- message-server
- git-access
namespace: merlin-icsl
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
