apiVersion: apps/v1
kind: Deployment
metadata:
  name: space-deployment
  namespace: merlin-icsl
spec:
  selector:
    matchLabels:
      app: space
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'merlin-icsl'
        vault.hashicorp.com/agent-inject-secret-compose-config.yml: 'internal/data/icsl/merlin'
        vault.hashicorp.com/agent-inject-secret-server.crt: 'internal/data/icsl/merlin'
        vault.hashicorp.com/agent-inject-secret-server.key: 'internal/data/icsl/merlin'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-perms-compose-config.yml: "0400"
        vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
        vault.hashicorp.com/agent-inject-perms-server.key: "0400"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/agent-inject-template-compose-config.yml: |  
          {{- with secret "internal/data/icsl/merlin" -}}  
          {{ .Data.data.spaceConf }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-server.crt: |  
          {{- with secret "internal/data/icsl/merlin" -}}  
          {{ .Data.data.ServerCrt }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-server.key: |  
          {{- with secret "internal/data/icsl/merlin" -}}  
          {{ .Data.data.ServerKey }}
          {{- end }}
      labels:
        app: space
    spec:
      serviceAccount: merlin-icsl
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: buildkitd
        image: moby/buildkit:master-rootless
        args:
          - --oci-worker-no-process-sandbox
        readinessProbe:
          exec:
            command:
              - buildctl
              - debug
              - workers
          initialDelaySeconds: 5
          periodSeconds: 30
        livenessProbe:
          exec:
            command:
              - buildctl
              - debug
              - workers
          initialDelaySeconds: 5
          periodSeconds: 30
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: Unconfined
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: 500m
            memory: 500Mi 
        volumeMounts:
          - mountPath: /home/user/.local/share/buildkit
            name: buildkitd
      - name: space 
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/gitea/merlin-space-test:main-5a3d7e
        imagePullPolicy: IfNotPresent
        env:
        - name: CONFIG_FILE
          value: /vault/secrets/compose-config.yml
        - name: LOG_PATH
          value: /var/log/space-server.log
        - name: IP
          value: "0.0.0.0"
        - name: PORT
          value: "8123"
        - name: REMOVE_CONFIG
          value: "true"
        - name: ENABLE_DEBUG
          value: "false"
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8123
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8123
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 2Gi 
        volumeMounts:
          - mountPath: /var/log/
            name: data-volume
          - mountPath: /tmp/
            name: tmp-volume
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
      volumes:
      - name: buildkitd
        emptyDir: {}
      - name: data-volume
        persistentVolumeClaim:
          claimName: space-log-encrypt-volume
      - name: tmp-volume
        persistentVolumeClaim:
          claimName: space-data-encrypt-volume