apiVersion: v1
kind: Service
metadata:
  name: git-access-service
  namespace: merlin
spec:
  ports:
  - name: http-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: git-access
  type: ClusterIP
