apiVersion: v1
kind: ConfigMap
metadata:
  name: website-configmap
  namespace: merlin-icsl
data:
  nginx.conf: |
    user $NGINX_USER;

    error_log /dev/stdout info;

    pid /var/run/nginx.pid;

    worker_processes 2;
    worker_rlimit_nofile 4096;
    events {
      use epoll;
      worker_connections 1024;
    }

    http {
      include /etc/nginx/mime.types;

      log_format main '[$time_local] remote_addr: $http_x_real_ip, request: "$request", '
      'status: $status, body_bytes_sent: $body_bytes_sent, http_referer: "$http_referer", '
      'http_user_agent: "$http_user_agent"';

      access_log /dev/stdout main;

      server_tokens off;

      autoindex off;

      port_in_redirect off;
      absolute_redirect off;

      client_header_buffer_size 1k;
      large_client_header_buffers 4 8k;
      client_body_buffer_size 1K;
      client_max_body_size 20k;

      client_header_timeout 60;
      client_body_timeout 60;
      client_body_in_file_only off;
      keepalive_timeout 300;
      send_timeout 60;

      proxy_hide_header X-Powered-By;
      proxy_request_buffering off;

      limit_conn_zone $binary_remote_addr zone=limitperip:10m;
      limit_req_zone $binary_remote_addr zone=ratelimit:10m rate=200r/s;

      gzip on;
      gzip_min_length 1k;
      gzip_buffers 4 16k;
      gzip_comp_level 5;
      gzip_types text/plain application/x-javascript text/css application/xml text/javascript application/javascript application/x-httpd-php application/json;
      gzip_vary on;

      map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
      }

      upstream gitea {
        server gitea-repo.gitea-repo-icsl.svc.cluster.local:3000;
      }
      server {
        listen 8080 ssl default_server;
        server_name modelfoundry-icsl.test.osinfra.cn;
        charset utf-8;

        add_header X-XSS-Protection "1; mode=block";
        add_header X-Frame-Options DENY;
        add_header X-Content-Type-Options nosniff;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
        add_header Content-Security-Policy "script-src 'self' *.baidu.com 'unsafe-inline' 'unsafe-eval'; object-src 'none'; frame-src https://cci.test.osinfra.cn:*";
        add_header Cache-Control "no-cache,no-store,must-revalidate";
        add_header Pragma no-cache;
        add_header Expires 0;
        add_header Referrer-Policy "no-referrer";

        limit_conn limitperip 10;
        ssl_session_tickets off;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:10m;

        ssl_certificate "cert/server.crt";
        ssl_certificate_key "cert/server.key";
        ssl_password_file "cert/abc.txt";
        ssl_dhparam "cert/dhparam.pem";
        ssl_ecdh_curve auto;
        ssl_protocols TLSv1.2;
        ssl_ciphers "ECDHE-RSA-AES256-GCM-SHA384";
        ssl_prefer_server_ciphers on;
        ssl_stapling on;
        ssl_stapling_verify on;
        resolver 8.8.8.8 8.8.4.4 valid=60s;
        resolver_timeout 5s;
        # valid_referers none blocked *.osinfra.cn;

        if ($request_method !~ ^(GET|HEAD|POST|PUT|DELETE)$) {
          return 444;
        }

        # if ($invalid_referer) {
        #   return 403;
        # }

        # location ~ /\. {
        #   deny all;
        #   return 404;
        # }
        location / {
          limit_req zone=ratelimit burst=2 nodelay;
          proxy_set_header X-Forwarded-For $http_x_real_ip;
          proxy_set_header Host $host;

          location /assets {
            add_header X-XSS-Protection "1; mode=block";
            add_header X-Frame-Options DENY;
            add_header X-Content-Type-Options nosniff;
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
            add_header Content-Security-Policy "script-src 'self' *.baidu.com 'unsafe-inline' 'unsafe-eval' ; object-src 'none'; frame-src 'none'";
            add_header Cache-Control "public,max-age=1209600";
            add_header Referrer-Policy "no-referrer";
          }

          location / {
            try_files $uri /index.html;
          }

          root /usr/share/nginx/www;
          index index.html;
        }


        location ^~ /server/ {
          limit_req zone=ratelimit burst=2 nodelay;
          proxy_set_header X-Forwarded-For $http_x_real_ip;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_ssl_verify	off;
          proxy_pass https://server-service.merlin-icsl.svc.cluster.local:8080/web/v1/;
        }

        location ^~ /api/ {
          limit_req zone=ratelimit burst=2 nodelay;
          proxy_set_header X-Forwarded-For $http_x_real_ip;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_ssl_verify	off;
          proxy_pass https://server-service.merlin-icsl.svc.cluster.local:8080/api/;
        }

        location ^~ /hook-delivery/ {
          limit_req zone=ratelimit burst=2 nodelay;
          proxy_set_header X-Forwarded-For $http_x_real_ip;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_ssl_verify	off;
          proxy_pass https://hookdelivery-service.merlin-icsl.svc.cluster.local:8080/;
        }

        location ^~ /api-file/ {
          limit_req zone=ratelimit burst=2 nodelay;
          proxy_set_header X-Forwarded-For $http_x_real_ip;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_ssl_verify	off;
          proxy_pass https://gitea-icsl.test.osinfra.cn/;
        }

        location ^~ /api-id/ {
          limit_req zone=ratelimit burst=2 nodelay;
          proxy_set_header X-Forwarded-For $http_x_real_ip;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_ssl_verify	off;
          proxy_pass https://modelfoundry-usercenter-icsl.test.osinfra.cn/;
        }

        location ^~ /api-dsapi/ {
          limit_req zone=ratelimit burst=2 nodelay;
          proxy_set_header X-Forwarded-For $http_x_real_ip;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_ssl_verify	off;
          proxy_pass https://dsapi.osinfra.cn/;
        }

        location ^~ /docs/ {
          limit_req zone=ratelimit burst=2 nodelay;
          proxy_set_header X-Forwarded-For $http_x_real_ip;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_ssl_verify	off;
          proxy_pass https://merlin-docs-service.merlin-icsl.svc.cluster.local:8080/;
        }

        location ^~ /coderepo/ {
          limit_req zone=ratelimit burst=2 nodelay;
          proxy_set_header X-Forwarded-For $http_x_real_ip;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_ssl_verify	off;
          proxy_pass https://git-access-service.merlin-icsl.svc.cluster.local:8080/;
        }

        location ~ ^/(?<username>[^/]+)/(?<reponame>[^/]+)(\.git)?/(?<api>info/lfs/.+|info/refs|HEAD|git-upload-pack|git-receive-pack|objects/.+) {
            set $reponame_with_git $reponame;
            if ($reponame !~ \.git) {
                set $reponame_with_git $reponame.git;
            }

            limit_req zone=ratelimit burst=2 nodelay;
            limit_rate 1m;
            proxy_pass https://gitea-icsl/$username/$reponame_with_git/$api$is_args$args;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $http_x_real_ip;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_ssl_verify	off;
        }

        error_page 401 402 403 405 406 407 413 414 /error.html;
        error_page 500 501 502 503 504 505 /error.html;

        location = /error.html {
          root /usr/share/nginx/www;
        }
      }
    }
