resources:
- deployment.yaml
commonAnnotations:
  kubernetes.ops.cluster: modelfoundry-guiyang-npu-containerd-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: Alpine
  kubernetes.ops.owner: wangxiyuan
  kubernetes.ops.region: guiyang
namespace: openmind-space-operator-system
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/modelfoundry-operator
  newTag: main-6c6c31
