resources:
- namespace.yaml
- sa.yaml
- networkpolicy.yaml
- merlin-server
- merlin-website
- merlin-docs
- hook-delivery
- label
- git-access
- space
namespace: merlin
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
