resources:
- deployment.yaml
commonAnnotations:
  kubernetes.ops.cluster: modelfoundry-guiyang-npu-containerd-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: "Alpine"
  kubernetes.ops.owner: wangxiyuan
  kubernetes.ops.region: guiyang
namespace: modelfoundry-operator-system

