---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merlin-docs
  namespace: merlin
spec:
  selector:
    matchLabels:
      app: merlin-docs
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: merlin-website
        vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
        vault.hashicorp.com/agent-inject-perms-server.key: "0400"
        vault.hashicorp.com/agent-inject-perms-abc.txt: "0400"
        vault.hashicorp.com/agent-inject-perms-dhparam.pem: "0400"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/secret-volume-path: "/etc/nginx/cert/"
        vault.hashicorp.com/agent-inject-secret-server.crt: "internal/data/infra-test/merlin-website"
        vault.hashicorp.com/agent-inject-template-server.crt: |
          {{- with secret "internal/data/infra-test/merlin-website" -}}
          {{ .Data.data.ServerCrt }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-server.key: "internal/data/infra-test/merlin-website"
        vault.hashicorp.com/agent-inject-template-server.key: |
          {{- with secret "internal/data/infra-test/merlin-website" -}}
          {{ .Data.data.ServerKey }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-abc.txt: "internal/data/infra-test/merlin-website"
        vault.hashicorp.com/agent-inject-template-abc.txt: |
          {{- with secret "internal/data/infra-test/merlin-website" -}}
          {{ .Data.data.certificatePassword }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-dhparam.pem: "internal/data/infra-test/merlin-website"
        vault.hashicorp.com/agent-inject-template-dhparam.pem: |
          {{- with secret "internal/data/infra-test/merlin-website" -}}
          {{ .Data.data.dhparamPem }}
          {{- end }}
      labels:
        app: merlin-docs
    spec:
      serviceAccount: merlin
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: merlin-docs
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/gitea/merlin-docs-test:main-e9b677
        imagePullPolicy: IfNotPresent
        env:
        - name: DET_URL
          value: https://modelfoundry-docs.test.osinfra.cn/docs/
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          httpGet:
            scheme: HTTPS
            path: /index.html
            port: 8080
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          httpGet:
            scheme: HTTPS
            path: /index.html
            port: 8080
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
